### ISSUE TITLE
文件不生效

### ISSUE THREAD

**Issue by banduoba** [liuchengxu/dotfiles#1]
`➜  ~ source .ideavimrc
.ideavimrc:1: bad math expression: operand expected at end of string
.ideavimrc:14: command not found:  clear the highlighted search result\nnnoremap <Leader>sc :nohlsearch<CR>\n\nnnoremap <Leader>fs :w<CR>\n\n
.ideavimrc:21: parse error near `\n'`

请问如下错误怎么解决

**Comment by liuchengxu** [comment]
`.ideavimrc` 是启动 IDEA 时自动读取的插件配置信息，不能在 terminal 中使用 `source` 命令。`.vimrc` 和 `.ideavimrc` 并不是一个概念。

**Comment by banduoba** [comment]
@liuchengxu 谢谢 确实可以了，不过有些快捷键好像失效，我是mac系统下，对了，如果我要增加其他快捷键，这个具体配置文件哪里有相应的参考么？

**Comment by liuchengxu** [comment]
你可以去看一下别人的 `.ideavimrc`, GitHub 搜索 ideavimrc ，更多内容的话 ，自行查看 [ideavim](https://github.com/JetBrains/ideavim) ，看它提供了什么功能，可以配置什么。

**Comment by banduoba** [comment]
@liuchengxu 谢谢
